[package]
name = "embrio-executor"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[dependencies.pin-utils]
version = "0.1.0-alpha.4"
default-features = false

[dependencies.tock]
path = "../libtock"
