[package]
name = "embrio-async-macros"
version = "0.1.0"
authors = ["Wim Looman <wim@nemo157.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.24"
quote = "0.6.10"
syn = { version = "0.15.26", features = ["full", "visit", "visit-mut", "parsing"] }
